---
language: node_js

node_js:
  - "8.7"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - ./node_modules/.bin/truffle develop && ./node_modules/.bin/truffle test

